# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'LemiAppTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LemiAppTest
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON', '~> 4.0'

  target 'LemiAppTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LemiAppTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
